// 灵砚导出系统 — TXT / EPUB

import JSZip from "jszip";

interface ExportChapter {
  order: number;
  title: string;
  body: string;
  wordCount: number;
}

interface ExportNovel {
  title: string;
  genre: string | null;
  synopsis: string | null;
  chapters: ExportChapter[];
}

// ============ TXT 导出 ============

export function exportTxt(novel: ExportNovel): string {
  const totalWords = novel.chapters.reduce((sum, ch) => sum + ch.wordCount, 0);
  const genreLabel = novel.genre || "未分类";

  const lines: string[] = [];
  lines.push(`《${novel.title}》`);
  lines.push(`类型：${genreLabel} | 总字数：${totalWords.toLocaleString()}`);
  lines.push("═".repeat(40));
  lines.push("");

  for (const ch of novel.chapters) {
    lines.push(`第${ch.order}章 ${ch.title}`);
    lines.push("─".repeat(30));
    lines.push(ch.body);
    lines.push("");
    lines.push("");
  }

  return lines.join("\n");
}

// ============ EPUB 导出 ============

function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function chapterToXhtml(order: number, title: string, body: string): string {
  // 将正文按段落分割，包装为 XHTML
  const paragraphs = body
    .split(/\n\s*\n/)
    .filter((p) => p.trim())
    .map((p) => `    <p>${escapeXml(p.trim())}</p>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-CN">
<head>
  <meta charset="UTF-8"/>
  <title>${escapeXml(title)}</title>
  <link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
  <h1>${escapeXml(title)}</h1>
${paragraphs}
</body>
</html>`;
}

function buildContentOpf(novel: ExportNovel, chapterFiles: string[]): string {
  const now = new Date().toISOString().split("T")[0];
  const totalWords = novel.chapters.reduce((sum, ch) => sum + ch.wordCount, 0);

  const manifestItems = chapterFiles
    .map((f, i) => `    <item id="chapter${i + 1}" href="${f}" media-type="application/xhtml+xml"/>`)
    .join("\n");

  const spineItems = chapterFiles
    .map((_, i) => `    <itemref idref="chapter${i + 1}"/>`)
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="bookid" version="3.0">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="bookid">urn:uuid:${crypto.randomUUID()}</dc:identifier>
    <dc:title>${escapeXml(novel.title)}</dc:title>
    <dc:language>zh-CN</dc:language>
    <dc:creator>灵砚 AI 写作助手</dc:creator>
    <dc:description>${escapeXml(novel.synopsis || "")}</dc:description>
    <dc:subject>${escapeXml(novel.genre || "")}</dc:subject>
    <dc:date>${now}</dc:date>
    <meta property="dcterms:modified">${now}T00:00:00Z</meta>
    <dc:rights>Generated by LingYan AI Writing Assistant</dc:rights>
  </metadata>
  <manifest>
    <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
    <item id="style" href="style.css" media-type="text/css"/>
${manifestItems}
  </manifest>
  <spine>
${spineItems}
  </spine>
</package>`;
}

function buildNav(novel: ExportNovel, chapterFiles: string[]): string {
  const tocItems = novel.chapters
    .map(
      (ch, i) =>
        `      <li><a href="${chapterFiles[i]}">第${ch.order}章 ${escapeXml(ch.title)}</a></li>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xml:lang="zh-CN">
<head>
  <meta charset="UTF-8"/>
  <title>目录</title>
  <link rel="stylesheet" type="text/css" href="style.css"/>
</head>
<body>
  <nav epub:type="toc" id="toc">
    <h1>目录</h1>
    <ol>
${tocItems}
    </ol>
  </nav>
</body>
</html>`;
}

const EPUB_STYLESHEET = `
body {
  font-family: "Noto Serif CJK SC", "Source Han Serif SC", "SimSun", serif;
  line-height: 1.8;
  margin: 1em;
  color: #333;
}
h1 {
  font-size: 1.5em;
  margin: 2em 0 1em;
  text-align: center;
  border-bottom: 1px solid #ddd;
  padding-bottom: 0.5em;
}
p {
  text-indent: 2em;
  margin: 0.5em 0;
}
`;

export async function exportEpub(novel: ExportNovel): Promise<Buffer> {
  const zip = new JSZip();

  // mimetype 必须是第一个文件，不压缩
  zip.file("mimetype", "application/epub+zip", { compression: "STORE" });

  // META-INF/container.xml
  zip.file(
    "META-INF/container.xml",
    `<?xml version="1.0" encoding="UTF-8"?>
<container xmlns="urn:oasis:names:tc:opendocument:xmlns:container" version="1.0">
  <rootfiles>
    <rootfile full-path="content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`
  );

  // 样式表
  zip.file("style.css", EPUB_STYLESHEET);

  // 章节文件
  const chapterFiles: string[] = [];
  for (let i = 0; i < novel.chapters.length; i++) {
    const ch = novel.chapters[i];
    const filename = `chapter${i + 1}.xhtml`;
    chapterFiles.push(filename);
    zip.file(filename, chapterToXhtml(ch.order, ch.title, ch.body));
  }

  // content.opf
  zip.file("content.opf", buildContentOpf(novel, chapterFiles));

  // nav.xhtml
  zip.file("nav.xhtml", buildNav(novel, chapterFiles));

  // 生成 ZIP
  const buffer = await zip.generateAsync({
    type: "nodebuffer",
    mimeType: "application/epub+zip",
    compression: "DEFLATE",
    compressionOptions: { level: 9 },
  });

  return buffer;
}
